services:
  postgres:
    image: postgres:15
    container_name: agilepath_db
    environment:
      POSTGRES_USER: ${JDBC_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      POSTGRES_DB: agilepath
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    env_file:
      - .env
    build:
      context: ./backend
    container_name: agilepath_backend
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile.${SPRING_PROFILES_ACTIVE}
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    container_name: agilepath_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
