-- Columns
create table sprint_columns (
    id           UUID        PRIMARY KEY,
    sprint_id    UUID        NOT NULL REFERENCES sprints (id) ON DELETE CASCADE,
    name         VARCHAR(255) NOT NULL,
    status       VARCHAR(50) NOT NULL, -- ENUM('TODO', 'IN_PROGRESS', 'DONE')
    column_index INT         GENERATED BY DEFAULT AS IDENTITY,
    CHECK(status IN ('TODO', 'IN_PROGRESS', 'DONE'))
);

-- Tasks
ALTER TABLE tasks DELETE COLUMN status;
ALTER TABLE tasks ADD COLUMN sprint_column_id UUID NOT NULL REFERENCES columns (id) ON DELETE CASCADE;