spring:
  config:
    activate:
      on-profile: dev

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jpa:
    show-sql: true

  logging:
    level:
      dev.ecckea.agilepath: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.flyway.core: DEBUG
