spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true

  logging:
    level:
      dev.ecckea.agilepath: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE