name: deploy

on:
  push:
    branches:
      - main
      - 4-docker

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          # SSH into the Azure VM and deploy
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << EOF
            cd /home/azureuser/agilepath || exit

            # Pull the latest changes from the main branch
            echo "Pulling latest changes from main branch..."
            git fetch origin 4-docker
            git pull origin 4-docker
            git switch 4-docker

            # Start Docker services for production with environment variables
            echo "Starting Docker services for production..."
            sudo docker compose --profile prod down && \
            JDBC_DATABASE_URL="${{ secrets.JDBC_DATABASE_URL }}" \
            JDBC_DATABASE_USERNAME="${{ secrets.JDBC_DATABASE_USERNAME }}" \
            JDBC_DATABASE_PASSWORD="${{ secrets.JDBC_DATABASE_PASSWORD }}" \
            REDIS_HOST="${{ secrets.REDIS_HOST }}" \
            REDIS_PORT="${{ secrets.REDIS_PORT }}" \
            CORS_ENABLED="${{ secrets.CORS_ENABLED }}" \
            CORS_ALLOWED_ORIGINS="${{ secrets.CORS_ALLOWED_ORIGINS }}" \
            CORS_ALLOWED_METHODS="${{ secrets.CORS_ALLOWED_METHODS }}" \
            CORS_ALLOWED_HEADERS="${{ secrets.CORS_ALLOWED_HEADERS }}" \
            CORS_ALLOW_CREDENTIALS="${{ secrets.CORS_ALLOW_CREDENTIALS }}" \
            CLERK_ISSUER="${{ secrets.CLERK_ISSUER }}" \
            SERVER_PORT="${{ secrets.SERVER_PORT }}" \
            VITE_BACKEND_URL="${{ secrets.VITE_BACKEND_URL }}" \
            VITE_CLERK_PUBLISHABLE_KEY="${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}" \
            SPRING_PROFILES_ACTIVE="prod" \
            LOG_LEVEL="INFO" \
            sudo docker compose --profile prod up -d
          EOF

      - name: clean up unused images
        run: |
          sudo docker image prune -f
